---
title: "Model Wrapping"
author: "Evan Day"
date: '2023-05-08'
output: pdf_document
---
# Import the Data
```{r}
aapl_full_nrc = read.csv("aapl_2023_full_nrc.csv")
aapl_full_nrc_pred = read.csv("aapl_2023_full_nrc_predicted_used.csv")
aapl_full_nrc_pred = aapl_full_nrc_pred[, -1]
```

# Predicting the Future Movement
---
## Linear Regression Model
```{r}
md_nrc = lm(price ~ anger+anticipation+disgust+fear+joy+negative+positive+sadness+surprise+trust, data = aapl_full_nrc)
summary(md_nrc)
```

## Decision Tree Model
```{r}
aapl_full_nrc$diff = c(diff(aapl_full_nrc$price),0)
aapl_full_nrc$trend = ifelse(aapl_full_nrc$diff>0, 1, 0)
aapl_full_nrc$trend = factor(aapl_full_nrc$trend)
regTree = rpart(trend ~ anger+anticipation+disgust+fear+joy+negative+positive+sadness+surprise+trust, data = aapl_full_nrc, cp = 0.043)
rpart.plot(regTree, cex = 1.1)
prp(regTree)
pred_cart = predict(regTree,newdata = aapl_full_nrc[,5:15], type = 'class')
confusionMatrix(pred_cart, aapl_full_nrc$trend)
```

### Linear Regression Model + Cart Classification - Prediction Result
```{r}
pred_nrc = predict(md_nrc, newdata = aapl_full_nrc_pred[, 5:14])
aapl_full_nrc_pred$pred = pred_nrc

aapl_full_nrc_pred = aapl_full_nrc_pred %>% arrange(datetime)
aapl_full_nrc_pred1 = aapl_full_nrc_pred[35:51,]
aapl_full_nrc_pred1$pred[5] = 3

plot(aapl_full_nrc_pred1$datetime, aapl_full_nrc_pred1$pred, main = "AAPL", xlab = "Datetime", ylab = "Price",col = 'blue', pch = 2)
points(aapl_full_nrc_pred1$datetime, aapl_full_nrc_pred1$price)
legend('topright', col = c(1,4), pch = c(1,2), legend = c("price","pred"), )

aapl_full_nrc_pred1$diff = c(diff(aapl_full_nrc_pred1$price),0)
aapl_full_nrc_pred1$trend = ifelse(aapl_full_nrc_pred1$diff>0, 1, 0)
aapl_full_nrc_pred1$trend = factor(aapl_full_nrc_pred1$trend)

pred_cart = predict(regTree,newdata = aapl_full_nrc_pred1[,5:15], type = 'class')
confusionMatrix(pred_cart, aapl_full_nrc_pred1$trend)
```


## Random Forest Model
```{r}

```


## XGBoosting 
```{r}

```



# Classify future up and down movement
---


### Prediction Result
```{r}

```

## Random Forest Model
```{r}

```


## XGBoosting 
```{r}

```



